version: '3.9'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  db-postgres:
    image: postgres:latest
    container_name: db-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

volumes:
  data: